project:
  type: website

website:
  title: "Micaela Chan"
  navbar:
    search: true
    left:
      - research_interest.qmd
      - href: resources/CV_MicaelaChan_20230207.pdf
        text: CV
      - blog.qmd
      - href: https://scholar.google.com/citations?user=x3rJjOAAAAAJ
        text: Google Scholar
      - icon: github
        href: https://github.com/mychan24
      - icon: twitter 
        href: https://twitter.com/micaela__chan
  page-footer: 
    center: "Micaela Chan, Ph.D"
    right:
      - icon: github
        href: https://github.com/mychan24
      - icon: twitter
        href: https://twitter.com/micaela__chan

format:
  html:
    smooth-scroll: true
    theme: flatly
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-after-body: static/googleanalytic.html
  
resources:
  - CNAME

editor: visual