project:
  type: website

website:
  title: "Micaela Chan"
  navbar:
    search: true
    left:
      - research_interest.qmd
      - blog.qmd
    right:
      - icon: "bi bi-file-earmark-person"
        href: resources/CV_MicaelaChan_20241021.pdf
        text: CV
      - icon: journal
        href: https://scholar.google.com/citations?user=x3rJjOAAAAAJ
        text: Google Scholar
      - icon: github
        text: GitHub
        href: https://github.com/mychan24
      - text: Connect
        menu:
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/micaela-chan/
        - text: ResearchGate
          href: https://www.researchgate.net/profile/Micaela-Chan
        - icon: twitter-x
          text: X
          href: https://x.com/micaela__chan     
  page-footer: 
    center: 
      - text: "Micaela Chan, Ph.D.  "
      - icon: github
        href: https://github.com/mychan24
      - icon: twitter-x
        href: https://x.com/micaela__chan
      - icon: linkedin
        href: https://www.linkedin.com/in/micaela-chan/

format:
  html:
    smooth-scroll: true
    theme: cosmo-dark
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-after-body: static/googleanalytic.html
  
resources:
  - CNAME

editor: visual