---
title: "Blog"
---

## [**Texas Counties\' Trend In  COVID-19 Positive-Test-Rate**](https://mychan24.shinyapps.io/covid_texas_county_trend_shiny/)

*7/7/2020*

-   Most website/summary reports COVID-19 positive test-rate at the state-level. This shiny dashboard plots COVID-19 positive test rate for Texas counties with \> 3000 total tests performed.

-   Data obtained from the [Texas Department of State Health Services](https://dshs.texas.gov/coronavirus/)

## [**COVID-19 Community Mobility Map (Data From Google)**](https://mychan24.github.io/covid19_google_mobility_map/)

4/26/2020

-   Plotting percentage change in visits to different category of places for each state

-   Data table of percent change visits extracted from [Google Community Mobility Report](https://www.google.com/covid19/mobility/)

-   Darker color indicates \'decrease\' in mobility

## [**Git & GitHub Ebook For Scientists (Bookdown)**](https://gitbookdown.dallasdatascience.com/)

*9/17/2019*

-   Brief introduction to Git & GitHub ebook (using [bookdown](https://bookdown.org/yihui/bookdown/))

-   Covers using Git for version control and sharing/collaborating on GitHub

-   Accompanied with Git & GitHub Workshop at CVL, Fall 2019.

## [**FMRI QC Plot In R** ](https://www.micaelachan.com/fMRI_QC_Plot)

*8/23/2019*

-   R code on how to make fMRI QC plot similar to those shown in [**Power, 2017 NeuroImage article.** ](https://linkinghub.elsevier.com/retrieve/pii/S1053-8119(16)30387-1)It aligns the fMRI time series by voxels/ROIs (bottom gray plot) with motion/signal QC plots (top), making it easy to spot global changes in fMRI signals and potentially relate them to motion or other signals.

-   It uses several small functions available on my GitHub repository, [**r-for-brain-network**](https://github.com/mychan24/r-for-brain-network)**.**
